# -*- coding: utf-8 -*-
"""project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15usfaswTVceDLLVfeRo57IiVQRhZ3AC1

In the first part I will be looking at every variable in the data set. In the second portion of the Project I enter a deeper dive into the data compaing the values.

####First part:
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("cost_of_living_us (2).csv")
df.dropna(inplace=True)
df.head()



1. case_id
2. state
3. isMetro
4. areaname
5. county
6. family_member_count
7. housing_cost
8. food_cost
9. transportation_cost
10. healthcare_cost
11. other_necessities_cost
12. childcare_cost
13. taxes
14. total_cost
15. median_family_income

"""### 1. `state` Distribution"""

plt.figure(figsize=(12, 6))
sns.countplot(x='state', data=df, palette='viridis', order=df['state'].value_counts().index)
plt.title('Distribution of Records by State')
plt.xlabel('State')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""Interpretation: This bar plot shows the number of records (combinations of family size and metropolitan status within counties) for each state. It indicates how many data points are available for each state in the dataset, which can vary significantly.

### 2. `isMetro` Distribution
"""

plt.figure(figsize=(7, 5))
sns.countplot(x='isMetro', data=df, palette='cividis')
plt.title('Distribution of Records by Metropolitan Status')
plt.xlabel('Is Metropolitan Area')
plt.ylabel('Count')
plt.xticks([0, 1], ['Non-Metro', 'Metro'])
plt.tight_layout()
plt.show()

"""**Interpretation:** This plot illustrates the count of records that fall within metropolitan (`True`) versus non-metropolitan (`False`) areas. It shows the balance of urban vs. rural data points in the dataset.

### 3. `areaname` Distribution (Top 15)
"""

plt.figure(figsize=(14, 7))
sns.countplot(x='areaname', data=df, palette='magma', order=df['areaname'].value_counts().head(15).index)
plt.title('Top 15 Most Frequent Area Names')
plt.xlabel('Area Name')
plt.ylabel('Count')
plt.xticks(rotation=60, ha='right')
plt.tight_layout()
plt.show()

"""**Interpretation:** Given the large number of unique area names, this graph displays the top 15 most frequently occurring area names in the dataset. It highlights which specific metropolitan or non-metropolitan areas are most represented.

### 4. `county` Distribution (Top 15)
"""

plt.figure(figsize=(14, 7))
sns.countplot(x='county', data=df, palette='plasma', order=df['county'].value_counts().head(15).index)
plt.title('Top 15 Most Frequent Counties')
plt.xlabel('County')
plt.ylabel('Count')
plt.xticks(rotation=60, ha='right')
plt.tight_layout()
plt.show()

"""**Interpretation:** Similar to 'areaname', this plot shows the top 15 counties with the most data entries. It gives an idea of which counties have more detailed breakdowns of cost data.

### 5. `family_member_count` Distribution
"""

plt.figure(figsize=(8, 5))
sns.countplot(x='family_member_count', data=df, palette='viridis', order=df['family_member_count'].value_counts().index)
plt.title('Distribution of Family Member Count')
plt.xlabel('Family Member Count Category')
plt.ylabel('Count')
plt.tight_layout()
plt.show()

"""**Interpretation:** This bar chart shows the frequency of different family member count categories (e.g., '1p0c' for one parent, zero children) within the dataset. It highlights the demographic composition covered by the cost data.

### 6. `housing_cost` Distribution
"""

plt.figure(figsize=(10, 6))
sns.histplot(df['housing_cost'], kde=True, bins=30, color='skyblue')
plt.title('Distribution of Housing Cost')
plt.xlabel('Housing Cost')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 2))
sns.boxplot(x=df['housing_cost'], color='skyblue')
plt.title('Box Plot of Housing Cost')
plt.xlabel('Housing Cost')
plt.tight_layout()
plt.show()

print(f"The average housing cost is: {average_housing_cost:.2f}")

housing_cost_range = max_housing_cost - min_housing_cost
print(f"The overall range of housing costs (Max - Min) is: {housing_cost_range:.2f}")

midpoint_of_range = (min_housing_cost + max_housing_cost) / 2
print(f"The midpoint of the housing cost range (average of Min and Max) is: {midpoint_of_range:.2f}")

"""**Interpretation:** The histogram shows the frequency of different housing cost ranges, revealing its overall distribution (e.g., skewed, normal). The box plot provides a summary of the central tendency, spread, and identifies potential outliers in housing costs.

### 7. `food_cost` Distribution
"""

plt.figure(figsize=(10, 6))
sns.histplot(df['food_cost'], kde=True, bins=30, color='lightcoral')
plt.title('Distribution of Food Cost')
plt.xlabel('Food Cost')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 2))
sns.boxplot(x=df['food_cost'], color='lightcoral')
plt.title('Box Plot of Food Cost')
plt.xlabel('Food Cost')
plt.tight_layout()
plt.show()

average_food_cost = df['food_cost'].mean()
min_food_cost = df['food_cost'].min()
max_food_cost = df['food_cost'].max()

print(f"The average food cost is: {average_food_cost:.2f}")

food_cost_range = max_food_cost - min_food_cost
print(f"The overall range of food costs (Max - Min) is: {food_cost_range:.2f}")

midpoint_of_range_food = (min_food_cost + max_food_cost) / 2
print(f"The midpoint of the food cost range (average of Min and Max) is: {midpoint_of_range_food:.2f}")

"""**Interpretation:** This set of plots visualizes the distribution of food costs. The histogram displays how food costs are spread across different values, while the box plot summarizes its median, quartiles, and any extreme values.

### 8. `transportation_cost` Distribution
"""

plt.figure(figsize=(10, 6))
sns.histplot(df['transportation_cost'], kde=True, bins=30, color='lightgreen')
plt.title('Distribution of Transportation Cost')
plt.xlabel('Transportation Cost')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 2))
sns.boxplot(x=df['transportation_cost'], color='lightgreen')
plt.title('Box Plot of Transportation Cost')
plt.xlabel('Transportation Cost')
plt.tight_layout()
plt.show()

average_transportation_cost = df['transportation_cost'].mean()
min_transportation_cost = df['transportation_cost'].min()
max_transportation_cost = df['transportation_cost'].max()

print(f"The average transportation cost is: {average_transportation_cost:.2f}")

transportation_cost_range = max_transportation_cost - min_transportation_cost
print(f"The overall range of transportation costs (Max - Min) is: {transportation_cost_range:.2f}")

midpoint_of_range_transportation = (min_transportation_cost + max_transportation_cost) / 2
print(f"The midpoint of the transportation cost range (average of Min and Max) is: {midpoint_of_range_transportation:.2f}")

"""**Interpretation:** These plots show the distribution of transportation costs. The histogram reveals the frequency of different cost ranges, and the box plot offers insights into the central tendency, variability, and outliers in transportation expenses.

### 9. `healthcare_cost` Distribution
"""

plt.figure(figsize=(10, 6))
sns.histplot(df['healthcare_cost'], kde=True, bins=30, color='gold')
plt.title('Distribution of Healthcare Cost')
plt.xlabel('Healthcare Cost')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 2))
sns.boxplot(x=df['healthcare_cost'], color='gold')
plt.title('Box Plot of Healthcare Cost')
plt.xlabel('Healthcare Cost')
plt.tight_layout()
plt.show()

average_healthcare_cost = df['healthcare_cost'].mean()
min_healthcare_cost = df['healthcare_cost'].min()
max_healthcare_cost = df['healthcare_cost'].max()

print(f"The average healthcare cost is: {average_healthcare_cost:.2f}")

healthcare_cost_range = max_healthcare_cost - min_healthcare_cost
print(f"The overall range of healthcare costs (Max - Min) is: {healthcare_cost_range:.2f}")

midpoint_of_range_healthcare = (min_healthcare_cost + max_healthcare_cost) / 2
print(f"The midpoint of the healthcare cost range (average of Min and Max) is: {midpoint_of_range_healthcare:.2f}")

"""**Interpretation:** The histogram and box plot illustrate the distribution of healthcare costs. This helps understand the typical range of healthcare expenses and identify any states or family configurations with unusually high or low costs.

### 10. `other_necessities_cost` Distribution
"""

plt.figure(figsize=(10, 6))
sns.histplot(df['other_necessities_cost'], kde=True, bins=30, color='mediumpurple')
plt.title('Distribution of Other Necessities Cost')
plt.xlabel('Other Necessities Cost')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 2))
sns.boxplot(x=df['other_necessities_cost'], color='mediumpurple')
plt.title('Box Plot of Other Necessities Cost')
plt.xlabel('Other Necessities Cost')
plt.tight_layout()
plt.show()

average_other_necessities_cost = df['other_necessities_cost'].mean()
min_other_necessities_cost = df['other_necessities_cost'].min()
max_other_necessities_cost = df['other_necessities_cost'].max()

print(f"The average other necessities cost is: {average_other_necessities_cost:.2f}")

other_necessities_cost_range = max_other_necessities_cost - min_other_necessities_cost
print(f"The overall range of other necessities costs (Max - Min) is: {other_necessities_cost_range:.2f}")

midpoint_of_range_other_necessities = (min_other_necessities_cost + max_other_necessities_cost) / 2
print(f"The midpoint of the other necessities cost range (average of Min and Max) is: {midpoint_of_range_other_necessities:.2f}")

"""**Interpretation:** These visualizations show the distribution of costs for 'other necessities'. The histogram displays the frequency of various cost brackets, and the box plot provides a statistical summary including potential outliers.

### 11. `childcare_cost` Distribution
"""

plt.figure(figsize=(10, 6))
sns.histplot(df['childcare_cost'], kde=True, bins=30, color='indianred')
plt.title('Distribution of Childcare Cost')
plt.xlabel('Childcare Cost')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 2))
sns.boxplot(x=df['childcare_cost'], color='indianred')
plt.title('Box Plot of Childcare Cost')
plt.xlabel('Childcare Cost')
plt.tight_layout()
plt.show()

average_childcare_cost = df['childcare_cost'].mean()
min_childcare_cost = df['childcare_cost'].min()
max_childcare_cost = df['childcare_cost'].max()

print(f"The average childcare cost is: {average_childcare_cost:.2f}")

childcare_cost_range = max_childcare_cost - min_childcare_cost
print(f"The overall range of childcare costs (Max - Min) is: {childcare_cost_range:.2f}")

midpoint_of_range_childcare = (min_childcare_cost + max_childcare_cost) / 2
print(f"The midpoint of the childcare cost range (average of Min and Max) is: {midpoint_of_range_childcare:.2f}")

"""**Interpretation:** The histogram illustrates the frequency of childcare costs across different ranges, while the box plot summarizes its central tendency and identifies any outliers. This helps in understanding the variability and typical cost for childcare.

### 12. `taxes` Distribution
"""

plt.figure(figsize=(10, 6))
sns.histplot(df['taxes'], kde=True, bins=30, color='darkorange')
plt.title('Distribution of Taxes')
plt.xlabel('Taxes')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 2))
sns.boxplot(x=df['taxes'], color='darkorange')
plt.title('Box Plot of Taxes')
plt.xlabel('Taxes')
plt.tight_layout()
plt.show()

average_taxes = df['taxes'].mean()
min_taxes = df['taxes'].min()
max_taxes = df['taxes'].max()

print(f"The average taxes is: {average_taxes:.2f}")

taxes_range = max_taxes - min_taxes
print(f"The overall range of taxes (Max - Min) is: {taxes_range:.2f}")

midpoint_of_range_taxes = (min_taxes + max_taxes) / 2
print(f"The midpoint of the taxes range (average of Min and Max) is: {midpoint_of_range_taxes:.2f}")

"""**Interpretation:** These plots show the distribution of taxes. The histogram provides insight into the frequency of different tax burdens, and the box plot summarizes the spread and identifies outliers, indicating states or areas with significantly different tax structures.

### 13. `total_cost` Distribution
"""

plt.figure(figsize=(10, 6))
sns.histplot(df['total_cost'], kde=True, bins=30, color='teal')
plt.title('Distribution of Total Cost')
plt.xlabel('Total Cost')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 2))
sns.boxplot(x=df['total_cost'], color='teal')
plt.title('Box Plot of Total Cost')
plt.xlabel('Total Cost')
plt.tight_layout()
plt.show()

import pandas as pd
df = pd.read_csv("cost_of_living_us (2).csv")
df.dropna(inplace=True)
display(df.head())

average_total_cost = df['total_cost'].mean()
min_total_cost = df['total_cost'].min()
max_total_cost = df['total_cost'].max()

print(f"The average total cost is: {average_total_cost:.2f}")

total_cost_range = max_total_cost - min_total_cost
print(f"The overall range of total costs (Max - Min) is: {total_cost_range:.2f}")

midpoint_of_range_total = (min_total_cost + max_total_cost) / 2
print(f"The midpoint of the total cost range (average of Min and Max) is: {midpoint_of_range_total:.2f}")

"""**Interpretation:** The histogram for total cost shows the overall distribution of the cost of living. The box plot gives a statistical summary, including the median total cost and the range, along with any unusually high or low total costs across the dataset.

### 14. `median_family_income` Distribution
"""

plt.figure(figsize=(10, 6))
sns.histplot(df['median_family_income'], kde=True, bins=30, color='darkcyan')
plt.title('Distribution of Median Family Income')
plt.xlabel('Median Family Income')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 2))
sns.boxplot(x=df['median_family_income'], color='darkcyan')
plt.title('Box Plot of Median Family Income')
plt.xlabel('Median Family Income')
plt.tight_layout()
plt.show()

average_median_family_income = df['median_family_income'].mean()
min_median_family_income = df['median_family_income'].min()
max_median_family_income = df['median_family_income'].max()

print(f"The average median family income is: {average_median_family_income:.2f}")

median_family_income_range = max_median_family_income - min_median_family_income
print(f"The overall range of median family income (Max - Min) is: {median_family_income_range:.2f}")

midpoint_of_range_median_family_income = (min_median_family_income + max_median_family_income) / 2
print(f"The midpoint of the median family income range (average of Min and Max) is: {midpoint_of_range_median_family_income:.2f}")

"""**Interpretation:** This set of plots visualizes the distribution of median family income. The histogram shows the frequency of different income levels, while the box plot summarizes its central tendency, spread, and helps identify any extreme income values within the dataset."""

# Install itables library (if not already installed)
!pip install itables

import itables
itables.show(df)

"""####Second Part:

1
"""

# This cell previously loaded 'df', but 'df' is now loaded earlier in the notebook.

"""2"""

# Install itables library (if not already installed)
!pip install itables

import itables
itables.show(df)

"""3. transportation, healthcare_cost, childcare_cost, taxes, median_family_income,
and family_member_count

###Analysis of Key Variables by State
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# df is already loaded in an earlier cell.

# Get a list of the unique states
unique_states = df['state'].unique()
print(f"Number of unique states found: {len(unique_states)}")

# Define the variables to analyze
continuous_vars = ['transportation_cost', 'healthcare_cost', 'childcare_cost', 'taxes', 'median_family_income']
categorical_var = 'family_member_count'

"""#### Distribution of Cost and Income Variables by State


"""

for var in continuous_vars:
    plt.figure(figsize=(15, 6))
    sns.boxplot(x='state', y=var, data=df, palette='viridis')
    plt.title(f'Distribution of {var.replace("_", " ").title()} by State')
    plt.xlabel('State')
    plt.ylabel(var.replace("_", " ").title())
    plt.xticks(rotation=45, ha='right')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

"""#### Distribution of Family Member Count by State

"""

g = sns.catplot(x=categorical_var, col='state', data=df, kind='count', col_wrap=4, height=4, aspect=1.2, palette='muted', sharey=False)
g.set_axis_labels("Family Member Count", "Count")
g.set_titles("State: {col_name}")
g.set_xticklabels(rotation=45, ha='right')
plt.suptitle('Distribution of Family Member Count by State', y=1.02) # Adjust suptitle position
plt.tight_layout(rect=[0, 0, 1, 0.98]) # Adjust layout to prevent suptitle overlap
plt.show()

"""4. Group this data by stateand draw a table by using colors for each state."""

import numpy as np

# Group by state and calculate the mean of numerical columns
# Exclude 'case_id' as it's an identifier, 'isMetro' is boolean
aggregated_df = df.groupby('state')[['housing_cost', 'food_cost', 'transportation_cost', 'healthcare_cost', 'other_necessities_cost', 'childcare_cost', 'taxes', 'total_cost', 'median_family_income']].mean().reset_index()

# Create a color map for states
num_states = len(aggregated_df['state'].unique())
colors = plt.cm.get_cmap('tab20', num_states) # Using 'tab20' colormap, which has 20 distinct colors
state_colors = {state: f'background-color: {plt.cm.colors.to_hex(colors(i))}'
                for i, state in enumerate(aggregated_df['state'].unique())}

def highlight_state_row(row):
    return [state_colors[row['state']]] * len(row)

# Apply the styling
styled_table = aggregated_df.style.apply(highlight_state_row, axis=1)

# Display the styled table
display(styled_table)

"""5. Draw a Choropleth for transportation_cost by State and compare resuls with graph in #3
above
"""

import plotly.express as px

fig = px.choropleth(aggregated_df,
                    locations='state',
                    locationmode='USA-states',
                    color='transportation_cost',
                    scope='usa',
                    color_continuous_scale='Viridis',
                    title='Average Transportation Cost by State (Choropleth Map)')

fig.update_layout(margin={"r":0,"t":50,"l":0,"b":0})
fig.show()

"""### Comparison with Box Plots

Comparing the map of 'transportation_cost' with the box plots generated in section 3:

*   Geographical Distribution: The choropleth map immediately highlights the geographical areas with higher or lower transportation costs, providing a quick visual summary of regional differences across the USA. For instance, states in certain regions (e.g., California, Northeast) might appear darker, indicating higher costs.
*   Range and Outliers (Box Plots): The box plots, on the other hand, provide a detailed view of the distribution within each state, including the median, interquartile range, and potential outliers. This level of detail about variability within a state is not visible in the choropleth map.
*   Overall vs. Detail: The choropleth excels at showing the overall pattern and spatial trends at a glance, while the box plots are better for understanding the statistical spread and central tendency of the cost variable for each individual state.

6. Draw plots for the followings and color them according to their state. Discuss their trends
and patterns.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# a. total_cost vs. transportation_cost
plt.figure(figsize=(12, 8))
sns.scatterplot(data=aggregated_df, x='transportation_cost', y='total_cost', hue='state', palette='tab20', s=100)
plt.title('Total Cost vs. Transportation Cost by State')
plt.xlabel('Average Transportation Cost')
plt.ylabel('Average Total Cost')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# b. childcare_cost vs. taxes
plt.figure(figsize=(12, 8))
sns.scatterplot(data=aggregated_df, x='taxes', y='childcare_cost', hue='state', palette='tab20', s=100)
plt.title('Childcare Cost vs. Taxes by State')
plt.xlabel('Average Taxes')
plt.ylabel('Average Childcare Cost')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# c. median_family_income vs. taxes
plt.figure(figsize=(12, 8))
sns.scatterplot(data=aggregated_df, x='taxes', y='median_family_income', hue='state', palette='tab20', s=100)
plt.title('Median Family Income vs. Taxes by State')
plt.xlabel('Average Taxes')
plt.ylabel('Average Median Family Income')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# d. housing_cost vs. taxes
plt.figure(figsize=(12, 8))
sns.scatterplot(data=aggregated_df, x='taxes', y='housing_cost', hue='state', palette='tab20', s=100)
plt.title('Housing Cost vs. Taxes by State')
plt.xlabel('Average Taxes')
plt.ylabel('Average Housing Cost')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Analysis of Trends and Patterns from Scatter Plots

Let's analyze the trends and patterns observed in the scatter plots:

a. Total Cost vs. Transportation Cost by State:
*   Trend: There appears to be a strong positive linear relationship between total cost and transportation cost. As transportation costs increase, the overall total cost of living also tends to increase. This suggests that transportation is a significant component of the total cost of living.
*   Patterns: States with higher transportation costs generally exhibit higher total costs. The coloring by state helps to identify if certain states or regions consistently have higher or lower values for both variables compared to others.

b. Childcare Cost vs. Taxes by State:
*   Trend: This plot might show a moderate positive correlation. States with higher average childcare costs also tend to have higher average taxes, but the relationship might not be as strong or as directly linear as total cost and transportation cost. There could be more variability.
*   Patterns: Some states might have disproportionately high childcare costs relative to their taxes, or vice-versa, indicating different policy priorities or cost structures. The distribution of states can reveal clusters or outliers in terms of these two cost components.

c. Median Family Income vs. Taxes by State:
*   Trend: A clear positive relationship is generally expected here. States with higher median family incomes tend to have higher average taxes. This reflects progressive tax systems and the fact that higher-income states often have a larger tax base.
*   Patterns: The spread of points can show how consistently income and taxes align across states. Outlier states might stand out if their median income is high but taxes are relatively low, or vice versa.

d. Housing Cost vs. Taxes by State:
*   Trend: There is likely a positive correlation between housing cost and taxes. Areas with higher property values (contributing to housing costs) often have higher property taxes, which contribute to the 'taxes' variable. Additionally, states with a higher cost of living (often driven by housing) may also have higher overall tax burdens.
*   Patterns: Similar to other plots, specific states might show deviations from the general trend. For example, some states might have very high housing costs but relatively lower taxes due to different revenue generation strategies, or vice-versa.

7. First 12 expensive Counties for childcare_cost
"""

# Calculate the average childcare_cost per county
county_childcare_cost = df.groupby('county')['childcare_cost'].mean().reset_index()

# Sort in descending order and get the top 12
top_12_expensive_counties = county_childcare_cost.sort_values(by='childcare_cost', ascending=False).head(12)

# Create the bar plot
plt.figure(figsize=(14, 7))
sns.barplot(x='county', y='childcare_cost', data=top_12_expensive_counties, palette='viridis')
plt.title('Top 12 Most Expensive Counties for Childcare Cost')
plt.xlabel('County')
plt.ylabel('Average Childcare Cost')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""8. First 12 high tax Counties"""

# Calculate the average taxes per county
counnty_taxes = df.groupby('county')['taxes'].mean().reset_index()

# Sort in descending order and get the top 12
top_12_high_tax_counties = counnty_taxes.sort_values(by='taxes', ascending=False).head(12)

# Create the bar plot
plt.figure(figsize=(14, 7))
sns.barplot(x='county', y='taxes', data=top_12_high_tax_counties, palette='plasma')
plt.title('Top 12 Counties with Highest Average Taxes')
plt.xlabel('County')
plt.ylabel('Average Taxes')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""Discussion of the Correlation Matrix Plot
The correlation matrix plot (heatmap) provides a visual representation of the linear relationships between pairs of numerical variables. Here's how to interpret it and what patterns we can observe:

Interpretation:

Values close to 1 (dark red/warm colors) indicate a strong positive correlation. This means that as one variable increases, the other tends to increase proportionally.
Values close to -1 (dark blue/cool colors) indicate a strong negative correlation. This means that as one variable increases, the other tends to decrease proportionally.
Values close to 0(lighter colors) indicate a weak or no linear correlation.
Observed Patterns:

Total Cost: As expected, total_cost shows very high positive correlations with almost all other cost components (e.g., housing_cost, food_cost, transportation_cost, healthcare_cost, childcare_cost, other_necessities_cost, and taxes). This makes sense as total_cost is an aggregate of these individual costs. This also validates that the individual cost components contribute significantly to the overall cost of living.
Strong Positive Correlations Among Cost Components: Many of the individual cost components (e.g., housing_cost, childcare_cost, taxes, transportation_cost) are positively correlated with each other. This suggests that states or areas with a higher cost of living in one category often have higher costs in other categories as well. For example, housing_cost and taxes often move together.
Median Family Income:median_family_income is generally positively correlated with various cost components and taxes. This implies that states with higher median incomes tend to have higher costs of living and higher tax burdens, reflecting a higher economic activity and possibly a higher standard of living.
Childcare Cost and Taxes: As seen in the scatter plot earlier, childcare_cost and taxes show a positive correlation, indicating that states with higher childcare costs often have higher average taxes.
Insights:

The heatmap confirms many of the relationships visually suggested by the scatter plots. For example, the strong positive correlation between total_cost and its components is clearly evident.
It helps identify which specific cost categories are most tightly linked. Understanding these correlations can be useful for policy-making (e.g., if you try to reduce one cost, how might it affect others) or for individuals comparing cost of living across states.

9. Draw a correlation matrix plot and discuss
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Calculate the correlation matrix for the numerical columns in aggregated_df
correlation_matrix = aggregated_df[['housing_cost', 'food_cost', 'transportation_cost', 'healthcare_cost', 'other_necessities_cost', 'childcare_cost', 'taxes', 'total_cost', 'median_family_income']].corr()

# Plot the correlation matrix as a heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Cost and Income Variables by State')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""Discussion of the Correlation Matrix Plot The correlation matrix plot (heatmap) provides a visual representation of the linear relationships between pairs of numerical variables. Here's how to interpret it and what patterns we can observe:

Interpretation:

Values close to 1 (dark red/warm colors) indicate a strong positive correlation. This means that as one variable increases, the other tends to increase proportionally. Values close to -1 (dark blue/cool colors) indicate a strong negative correlation. This means that as one variable increases, the other tends to decrease proportionally. Values close to 0(lighter colors) indicate a weak or no linear correlation. Observed Patterns:

Total Cost: As expected, total_cost shows very high positive correlations with almost all other cost components (e.g., housing_cost, food_cost, transportation_cost, healthcare_cost, childcare_cost, other_necessities_cost, and taxes). This makes sense as total_cost is an aggregate of these individual costs. This also validates that the individual cost components contribute significantly to the overall cost of living. Strong Positive Correlations Among Cost Components: Many of the individual cost components (e.g., housing_cost, childcare_cost, taxes, transportation_cost) are positively correlated with each other. This suggests that states or areas with a higher cost of living in one category often have higher costs in other categories as well. For example, housing_cost and taxes often move together. Median Family Income:median_family_income is generally positively correlated with various cost components and taxes. This implies that states with higher median incomes tend to have higher costs of living and higher tax burdens, reflecting a higher economic activity and possibly a higher standard of living. Childcare Cost and Taxes: As seen in the scatter plot earlier, childcare_cost and taxes show a positive correlation, indicating that states with higher childcare costs often have higher average taxes. Insights:

The heatmap confirms many of the relationships visually suggested by the scatter plots. For example, the strong positive correlation between total_cost and its components is clearly evident. It helps identify which specific cost categories are most tightly linked. Understanding these correlations can be useful for policy-making (e.g., if you try to reduce one cost, how might it affect others) or for individuals comparing cost of living across states.

10. Fit a regression line for total_cost and taxes
"""

import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import linregress

# Extract data for regression
x = aggregated_df['taxes']
y = aggregated_df['total_cost']

# Perform linear regression
slope, intercept, r_value, p_value, std_err = linregress(x, y)

# Create the scatter plot
plt.figure(figsize=(12, 8))
sns.scatterplot(x=x, y=y, data=aggregated_df, hue='state', palette='tab20', s=100)

# Plot the regression line
plt.plot(x, intercept + slope * x, color='red', linestyle='--', label=f'Regression Line (R-squared = {r_value**2:.2f})')

plt.title('Total Cost vs. Taxes with Regression Line by State')
plt.xlabel('Average Taxes')
plt.ylabel('Average Total Cost')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

print(f"Slope: {slope:.2f}")
print(f"Intercept: {intercept:.2f}")
print(f"R-squared: {r_value**2:.2f}")
print(f"P-value: {p_value:.3f}")

11. Check outliers for food_cost by state and discuss

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15, 7))
sns.boxplot(x='state', y='food_cost', data=df, palette='viridis')
plt.title('Distribution of Food Cost by State with Outliers')
plt.xlabel('State')
plt.ylabel('Food Cost')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Discussion of Outliers in Food Cost by State

The box plot above visualizes the distribution of `food_cost` for each state and helps in identifying potential outliers. Here's how to interpret the plot for outliers:

*   Box Plot Components:
    *   The box itself represents the interquartile range (IQR), spanning from the 25th percentile (Q1) to the 75th percentile (Q3) of food costs within that state.
    *   The line inside the box is the median (50th percentile).
    *   The "whiskers" extend from the box to the minimum and maximum values within 1.5 times the IQR from Q1 and Q3, respectively.
    *   Points beyond the whiskers are considered potential outliers. These represent individual data points (likely specific counties or family configurations within a state) where the food cost is significantly higher or lower than the typical range for that state.

*   Observed Outliers:
    *   By examining the plot, you can identify states that have individual dots outside their whiskers. These dots indicate records (e.g., a specific county and family size combination) with unusually high or low food costs compared to the majority of data points within that state.
    *   For example, if you see several dots far above the upper whisker for a particular state, it suggests that there are instances of very high food costs in that state that deviate significantly from the norm.

*   Potential Causes for Outliers:
    *   High Cost of Living Areas: Outliers with extremely high food costs could represent very expensive cities or regions within a state, where prices for goods and services, including food, are generally inflated.
    *   Specific Family Configurations: The `family_member_count` variable could also play a role. Larger families might naturally have higher food costs, and if such a configuration is an outlier within a state, it would appear as such.
    *   Data Entry Errors: In some cases, outliers can also be indicative of data entry errors or anomalies that might require further investigation.

*   Insights: Identifying these outliers can be valuable. For policy makers, it could highlight specific areas within a state that face disproportionately high food expenses. For individuals, it could inform decisions about where to live based on cost of living differences even within the same state.

12. Draw a bubble plot for food_cost and taxes while the size and color are based on
childcare_cost and isMetro, respectively.
"""

import plotly.express as px

# Determine state-level isMetro status: True if any county in the state is metro
state_is_metro = df.groupby('state')['isMetro'].any().reset_index()
state_is_metro['isMetro_category'] = state_is_metro['isMetro'].map({True: 'Metro', False: 'Non-Metro'})

# Merge this information into the aggregated_df
bubble_plot_df = aggregated_df.merge(state_is_metro[['state', 'isMetro_category']], on='state', how='left')

# Create the bubble plot
fig = px.scatter(bubble_plot_df,
                 x='taxes',
                 y='food_cost',
                 size='childcare_cost',
                 color='isMetro_category',
                 hover_name='state',
                 title='Food Cost vs. Taxes by State (Childcare Cost as Size, Metro Status as Color)',
                 labels={'taxes': 'Average Taxes',
                         'food_cost': 'Average Food Cost',
                         'childcare_cost': 'Average Childcare Cost',
                         'isMetro_category': 'Metro Status'})

fig.update_layout(height=600)
fig.show()

"""13. Draw a bubble plot for housing_cost and taxes while the size and color are based on
transportation_cost and state, respectively.
"""

import plotly.express as px

# Create the bubble plot
fig = px.scatter(aggregated_df,
                 x='taxes',
                 y='housing_cost',
                 size='transportation_cost',
                 color='state',
                 hover_name='state',
                 title='Housing Cost vs. Taxes by State (Transportation Cost as Size, State as Color)',
                 labels={'taxes': 'Average Taxes',
                         'housing_cost': 'Average Housing Cost',
                         'transportation_cost': 'Average Transportation Cost'},
                 size_max=60)

fig.update_layout(height=600)
fig.show()

"""14. 3D Plot for transportation, healthcare_cost, and childcare_cost"""

import plotly.express as px

fig = px.scatter_3d(aggregated_df,
                    x='transportation_cost',
                    y='healthcare_cost',
                    z='childcare_cost',
                    color='state',
                    hover_name='state',
                    title='3D Plot of Transportation, Healthcare, and Childcare Costs by State',
                    labels={'transportation_cost': 'Average Transportation Cost',
                            'healthcare_cost': 'Average Healthcare Cost',
                            'childcare_cost': 'Average Childcare Cost'})

fig.update_layout(height=700)
fig.show()

"""15. 3D Plot for childcare_cost, taxes, median_family_income, and state

"""

import plotly.express as px

fig = px.scatter_3d(aggregated_df,
                    x='childcare_cost',
                    y='taxes',
                    z='median_family_income',
                    color='state',
                    hover_name='state',
                    title='3D Plot of Childcare Cost, Taxes, and Median Family Income by State',
                    labels={'childcare_cost': 'Average Childcare Cost',
                            'taxes': 'Average Taxes',
                            'median_family_income': 'Average Median Family Income'})

fig.update_layout(height=700)
fig.show()

"""16. Use PCA for 3 components

"""

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Select the relevant numerical columns for PCA
pca_features = aggregated_df[['housing_cost', 'food_cost', 'transportation_cost', 'healthcare_cost', 'other_necessities_cost', 'childcare_cost', 'taxes', 'median_family_income']]

# Standardize the data before applying PCA
scaler = StandardScaler()
scaled_features = scaler.fit_transform(pca_features)

# Apply PCA with 3 components
pca = PCA(n_components=3)
pca_components = pca.fit_transform(scaled_features)

# Create a DataFrame for the PCA components
pca_df = pd.DataFrame(data = pca_components,
                      columns = ['PC1', 'PC2', 'PC3'])

# Add the state names back to the PCA DataFrame for identification
pca_df['state'] = aggregated_df['state']

# Display the explained variance ratio by each principal component
print("Explained Variance Ratio:")
for i, exp_var in enumerate(pca.explained_variance_ratio_):
    print(f"Principal Component {i+1}: {exp_var:.2f}")

# Display the first few rows of the PCA DataFrame
print("\nPCA Components DataFrame:")
display(pca_df.head())

"""17. Use NMF 3 components

"""

from sklearn.decomposition import NMF
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

# Select the relevant numerical columns for NMF (same as PCA features)
nmf_features = aggregated_df[['housing_cost', 'food_cost', 'transportation_cost', 'healthcare_cost', 'other_necessities_cost', 'childcare_cost', 'taxes', 'median_family_income']]

# Scale the data to a [0, 1] range to ensure non-negativity for NMF
scaler_nmf = MinMaxScaler()
scaled_nmf_features = scaler_nmf.fit_transform(nmf_features)

# Apply NMF with 3 components
nmf = NMF(n_components=3, random_state=42, init='random', max_iter=1000)
nmf_components = nmf.fit_transform(scaled_nmf_features)

# Create a DataFrame for the NMF components
nmf_df = pd.DataFrame(data = nmf_components,
                      columns = ['NMF1', 'NMF2', 'NMF3'])

# Add the state names back to the NMF DataFrame for identification
nmf_df['state'] = aggregated_df['state']

# Display the first few rows of the NMF DataFrame
print("NMF Components DataFrame:")
display(nmf_df.head())

# Optionally, display the feature loadings (components_ attribute)
print("\nNMF Feature Loadings (components_ attribute - weights for each original feature in each NMF component):")
display(pd.DataFrame(nmf.components_, columns=nmf_features.columns, index=['NMF1', 'NMF2', 'NMF3']))

