# -*- coding: utf-8 -*-
"""project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15usfaswTVceDLLVfeRo57IiVQRhZ3AC1

1
"""

import pandas as pd

df = pd.read_csv("cost_of_living_us (2).csv")
df.dropna(inplace=True)
df.dropna(inplace=True)
df.head()

"""2 had ai help"""

# Install itables library (if not already installed)
!pip install itables

import itables
itables.show(df)

"""3. transportation, healthcare_cost, childcare_cost, taxes, median_family_income,
and family_member_count
"""

